
CREATE DATABASE ESCOLA;
USE             ESCOLA;

CREATE TABLE DISCIPLINA (
   IDDISC INT NOT NULL PRIMARY KEY,
   NOME   VARCHAR(40)
);

CREATE TABLE ALUNO (
   RA     INT NOT NULL PRIMARY KEY,
   NOME   VARCHAR(50),
   FONE   VARCHAR(20),
   ENDER  VARCHAR(60)
);

CREATE TABLE NOTA (
   RA     INT NOT NULL,
   IDDISC INT NOT NULL,
   NOTA1  DOUBLE,
   NOTA2  DOUBLE,
   NOTA3  DOUBLE,

   PRIMARY KEY(RA,IDDISC),
   FOREIGN KEY(IDDISC) REFERENCES DISCIPLINA(IDDISC),
   FOREIGN KEY(RA) REFERENCES ALUNO(RA)
);
